#!/bin/bash


cd ./ESN-Output-Feedback
python3 esn_train.py
python3 esn_test.py
python3 output_to_midi_csv.py
mv result.txt ../Final-Step/result.txt
cd ../Final-Step
python3 replace_drums.py
csvmidi result.csv result.mid
