#!/bin/bash


FILES=*.csv
start=$SECONDS
counter=0



for f in $FILES;
do
  python3 CSV-to-Network.py "$f"
  let counter=counter+1
  echo "Did " $counter "files so far."
  echo "Time passed: " $SECONDS " seconds."
done;
